{
 "title": "StorageGroup-Performance",
 "time": { "from": "2019-08-17T21:34:02.951Z", "to": "2019-08-17T22:59:41.621Z" },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "Storage Group+VMAX-StorageGroup+IORate",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "响应时间(ms)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "Storage Group+VMAX-StorageGroup+ResponseTime",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "Storage Group+VMAX-StorageGroup+ReadThroughput",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "Storage Group+VMAX-StorageGroup+WriteThroughput",
     "type": "timeseries"
    }
   ]
  }
 ]
}