---
- hosts: localhost
  vars:
    input: &uni_connection_vars
      unity_hostname: "{{ unity_hostname }}"
      unity_username: "{{ unity_username }}"
      unity_password: "{{ unity_password }}"

    pool_name: "{{ unity_pool_name }}"
    vol_name: "{{ unity_vol_name }}"
    vol_capacity: "{{ capacity }}"

  tasks:
    - name: Query the storage pool id
      dellemc_unity:
        <<: *uni_connection_vars
        unity_updates:
        unity_password_updates:
        unity_queries:
          - { resource_type: pool , fields: "name" , filter: "name lk \"{{ unity_pool_name }}\" " }
      register: pools
    # - debug: var=pools.unity_query_results[0].entries[0]
    - debug: var=pools.unity_query_results[0].entries[0].id


    - name: Query the host id
      dellemc_unity:
        <<: *uni_connection_vars
        unity_updates:
        unity_password_updates:
        unity_queries:
          - { resource_type: host , fields: "name" , filter: "name lk \"{{ unity_host_name }}\" " }
      register: hosts
    - debug: var=hosts.unity_query_results[0].entries[0].id


    - name: create a new lun
      dellemc_unity:
        <<: *uni_connection_vars
        unity_updates: 
          - {resource_type: storageResource,
             "name": "{{vol_name}}",
             "lunParameters":{ "pool":{ "id":"{{ pools.unity_query_results[0].entries[0].id }}" }, "hostAccess":[ { "host":{ "id":"{{ hosts.unity_query_results[0].entries[0].id }}" }, "accessMask":1 } ], "isThinEnabled":false , "isCompressionEnabled":false, "size": " {{ vol_capacity }} " } ,
             action: 'createLun'}
      register: result

    - name: RESPONSE
      dellemc_unity:
        <<: *uni_connection_vars
        unity_updates:
        unity_password_updates:
        unity_queries:
          - { resource_type: lun, fields: "name,wwn", filter: "name lk \"{{ vol_name }}\" " }
      register: volinfo


